version: 0.0
os: linux
files:
    - source: /
      destination: /var/www/html
hooks:
    AfterInstall:
        - location: scripts/install_pro.sh
          timeout: 300
          runas: root
    ApplicationStart:
        - location: scripts/start_serve.sh
          timeout: 300
          runas: root
